apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proyecto1-front-ingress
  namespace: press
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: public
  rules:
    - host: 10.43.103.200.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proyecto1-front
                port:
                  number: 80
